### ISSUE TITLE
hexToColor : String -> Result String Color

### ISSUE THREAD

**Issue by toastal** [eskimoblood/elm-color-extra#13]
http://package.elm-lang.org/packages/elm-lang/core/5.0.0/String#conversions

Similar to the String conversion, `hexToColor` should return a `Result` rather than a `Maybe`.

**Comment by eskimoblood** [comment]
What problem does it solve?

**Comment by toastal** [comment]
Consistency with the `core`. Things that parse and fail return results like JSON, etc. And actually since it's already namespaced to something color-related, `fromHex` might make a better name.

**Comment by eskimoblood** [comment]
merged and published thanks
