### ISSUE TITLE
improvement request:  add hexOrBlack for better dealing with result type

### ISSUE THREAD

**Issue by AionDev** [eskimoblood/elm-color-extra#19]
I have an idea for a small improvement. `hex` function is neded a lot in my code - but dealing with result unwrapping all over the place it's not ideal. I think it's useful if you provide a function like this already built in the library:
```
import Color.Convert as EColor  -- extra color... 
import Color exposing (Color)

hexOrBlack : String -> Color
hexOrBlack colorCode =
    EColor.hexToColor colorCode
        |> Result.withDefault Color.black
```
```
background <| hexOrBlack "EDEDED"   -- a nice gray color
background <| hexOrBlack "ED_EDED"   -- black color
```
Maybe a better name, and maybe do it for both - for white and for black.  Thank you :smile:

**Comment by eskimoblood** [comment]
Thanks for the feature request. But I think this is something that everyone can implement by itself. Also next time someone needs red or green as default, so this will not scale.
