### ISSUE TITLE
Some examples would go a long way

### ISSUE THREAD

**Issue by dstreet26** [eskimoblood/elm-color-extra#20]
For developers trying to integrate this into their apps, it would be great to see some small snippets of how this code is used (Like [Elm's List docs](http://package.elm-lang.org/packages/elm-lang/core/5.1.1/List))

**Comment by eskimoblood** [comment]
Please feel free to add a pull request. Or at least tell me what is unclear, as a lot of the function have examples.

**Comment by dstreet26** [comment]
Oops, I didn't see some of the examples. And honestly as I work with this library it seems straightforward.

I'm working on an interactive Elm Color Demo page showing off Core.Colors and this repo. If it turns out well, maybe you can link to it or add it to this repo eventually. 

I still tried my hand at a [PR](https://github.com/eskimoblood/elm-color-extra/pull/21). I will probably add more to the PR as stuff comes up. I'm new to open source contributions.

This issue can be closed since there already are examples.

**Comment by eskimoblood** [comment]
Thanks for expanding the docs. I would real love to have some interactive docs, as well. Worked on it for while but never finished it.

**Comment by dstreet26** [comment]
Yeah that's what I'm going for! Definitely a good way to learn more Elm

**Comment by dstreet26** [comment]
The gif only shows a few blend modes and stuff but the demo I'm working on has more.

The idea is that the user gets 2 random colors when they load the page, they can change them with the color pickers. Eventually this demo can have all the features of Elm.Color and elm-color extra and they layout can be greatly improved. What do you think?

![video_2017-10-28_11_13_22](https://user-images.githubusercontent.com/6311278/32135707-803afb46-bbd1-11e7-9719-6968b88cf50a.gif)
