### ISSUE TITLE
Transparent colors aren't converted to hex properly (alpha is dropped)

### ISSUE THREAD

**Issue by Janiczek** [eskimoblood/elm-color-extra#23]
The function concerned is [`colorToHex`](https://github.com/eskimoblood/elm-color-extra/blob/84840ee577b56e491597fd0a06771e3d8ee2be79/src/Color/Convert.elm#L177-L191). Ignores the `alpha` field of the `toRgb` record and it probably shouldn't.

Here's a relevant [caniuse.com chart](https://caniuse.com/#feat=css-rrggbbaa).
The best solution is probably to generate a `#rrggbb` if alpha == 1 and `#rrggbbaa` otherwise?

This issue surfaced in https://github.com/terezka/line-charts/issues/40.

**Comment by eskimoblood** [comment]
@Janiczek  could you please add a pull request for this, as I have no time to work on this at the moment.
